### ISSUE TITLE
Status of Singularity BioContainers project

### ISSUE THREAD

**Issue by marcodelapierre** [BioContainers/singularity-build-bot#1]
Hi @bgruening , just wandering what is the current status of this? 
I see that most of the images at https://depot.galaxyproject.org/singularity/  
have quite an old timestamp; the new/ subdirectory seems to have newer stuff.
Also, will you be moving to the SIF format any time soon?
And finally, are you planning to provide links to Singularity images in the Biocontainers registry website?
Many thanks, Marco

**Comment by bgruening** [comment]
The new once are all rebuild with Singularity 3 (https://depot.galaxyproject.org/singularity/new/) and will be moved in the main dir soon. The plan is to have them available on CVMFS as well, soon, so that usegalaxy.eu can use them for almost all tools. All containers are in sif format and the links will be included in the webpage ... but the idea is more that we guarantee that for all Docker containers there is a Singularity container available.

Does this answer help? :)
Cheers,
Bjoern

**Comment by marcodelapierre** [comment]
Yep, thanks Bjoern!
